# Site settings
title: Felipe Nogueira # <title> tag content
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://felipenogueira3d.com" # the base hostname & protocol for your site
description: "Felipe Nogueira's personal website."
permalink: /posts/:title/
# paginate: 10
# paginate_path: /posts/page/:num/

# porject settings
portfolio_dir: projects
skip_related_projects: true

# Social accounts
email: "felipe@felipenogueira3d.com"
github: "https://github.com/pepetd"
youtube: "https://www.youtube.com/user/TheDragoon"
vimeo: "https://vimeo.com/pepetd"
linkedin: "http://www.linkedin.com/in/pepetd"

# Build settings
# sass:
#   sass_dir: _scss
#   style: compressed

# Exclude these files
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md"]

# Markdown library
markdown: redcarpet

# Use Pygments to highlight code blocks
highlighter: pygments

# required gems to load
gems:
- jekyll-sitemap
- sass-globbing
- sass-rails
- autoprefixer-rails
- jekyll-assets
- uglifier

# assets:
#   compress:
#     css: false
#     js: false
#   digest: false
