source "http://rubygems.org"
ruby "2.3.0"

gem "jekyll", "2.4.0"
gem "jekyll-assets", "1.0.0"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "sass"
gem "octopress-autoprefixer"
gem "uglifier"
gem "redcarpet"
gem "pygments.rb"
