---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  posts:
    default_front_matter_template: posts
  pages:
    default_front_matter_template: pages
  projects:
    default_front_matter_template: projects
version: 0.18.1
