---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  hidden: false
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
  default: now
- name: image
  type: file
  config:
    maxSize: '10'
  label: Image
- name: categories
  type: tag_list
  default: []
  label: Categories
- name: tags
  type: tag_list
  default: []
  label: Tags
- type: text
  name: type
  label: Type
  hidden: true
  config:
    required: true
  default: project
- type: text
  name: layout
  label: Layout
  hidden: true
  config:
    required: true
  default: single
pages:
- content/projects/yahoo-using-your-yahoo.md
- content/projects/brawny-lean-on-me.md
- content/projects/clubhouse-mothers-little-helper.md
- content/projects/colgate-360-activeflex.md
- content/projects/garanimals-mix-match-save.md
- content/projects/infinity-grebullon.md
- content/projects/infinity-grebullon-outtake-door.md
- content/projects/infinity-remulak.md
- content/projects/invigor-live-for-invigor.md
- content/projects/koei-warriors-legends-of-troy.md
- content/projects/redrover-death-dodge.md
- content/projects/robinhood-county-fair.md
- content/projects/sasktel-bundles.md
- content/projects/sasktel-expressions.md
- content/projects/sasktel-gainers-max-bowl.md
- content/projects/sasktel-hang-loose.md
- content/projects/sasktel-once-upon-a-dream.md
- content/projects/sasktel-raving-red.md
- content/projects/sasktel-river-ride.md
- content/projects/sasktel-the-ride.md
- content/projects/tendril-coke.md
- content/projects/tendril-fck-wntr.md
- content/projects/tendril-s-m-l.md
- content/projects/toblerone-christmas.md
